import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import { AppContextProvider } from '@/context'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn('min-h-dvh bg-background text-foreground antialiased', inter.className)}>
        <AppContextProvider>
          <main className='flex min-h-dvh flex-col'>{children}</main>
        </AppContextProvider>
      </body>
    </html>
  )
}
